services:

  postgres:
    image: postgres:17
    container_name: cammanager-db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./database:/var/lib/postgresql/data

  backend:

    build: ./backend

    container_name: cammanager-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - postgres

